// supabase-js-v2/user-management/nextjs-ts-user-management/components/Auth.tsx
import { useState } from 'react'
import { supabase } from '../lib/supabaseClient'
// import styles from '../styles/Auth.module.css'

export default function Auth({}) {
  const [loading, setLoading] = useState(false)
  const [email, setEmail] = useState('')

  const handleLogin = async (email: string) => {
    try {
      setLoading(true)
      // const { error, user } = await supabase.auth.signIn({ email })
      const { error, data } = await supabase.auth.signInWithOtp({ email })
      if (error) throw error
      alert('Check your email for the login link!')
    } catch (error) {
      if (error instanceof Error) {
        console.log('Error thrown:', error.message)
        alert(error.message)
      }
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="row">
      <div className="col-6">
        <h1 className="header">Supabase Auth + Storage</h1>
        <p className="">
          Experience our Auth and Storage through a simple profile management example. Create a user
          profile and upload an avatar image. Fast, simple, secure.
        </p>
      </div>
      <div className="col-6 auth-widget">
        <p className="description">Sign in via magic link with your email below</p>
        <div>
          <input
            className="inputField"
            type="email"
            placeholder="Your email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
          />
        </div>
        <div>
          <button
            onClick={(e) => {
              e.preventDefault()
              handleLogin(email)
            }}
            className={'button block'}
            disabled={loading}
          >
            {loading ? <img className="loader" src="loader.svg" /> : <span>Send magic link</span>}
          </button>
        </div>
      </div>
    </div>
  )
}

// supabase-js-v2/user-management/nuxtjs-user-management/components/Auth.vue
<template>
  <div class="row">
    <div class="col-6">
      <h1 class="header">Supabase Auth + Storage</h1>
      <p className="">
        Experience our Auth and Storage through a simple profile management example. Create a user
        profile and upload an avatar image. Fast, simple, secure.
      </p>
    </div>
    <form class="col-6 auth-widget" @submit.prevent="handleSubmit">
      <p class="description">Sign in via magic link with your email below</p>
      <div>
        <label for="email-register">Email</label>
        <input
          class="inputField"
          v-model="formValues.email"
          id="email-register"
          type="email"
          placeholder="Your email"
        />
      </div>

      <div>
        <button class="button block" :disabled="formValues.loader">
          {{ formValues.loader ? "Loading ..." : "Sign up with magic link" }}
        </button>
      </div>
    </form>
  </div>
</template>

<script>
import { supabase } from "../lib/supabaseClient";

export default {
  data() {
    return {
      formValues: {
        email: "",
        loader: false,
      },
    };
  },
  methods: {
    async handleSubmit() {
      console.log("ENV", process.env.NUXT_PUBLIC_SUPABASE_URL);
      try {
        this.formValues.loader = true;
        const { error, data: { user } } = await supabase.auth.signInWithOtp({
          email: this.formValues.email,
        });

        if (error) {
          throw error;
        }

        alert("Check your email for the login link!");
      } catch (error) {
        alert(error.message);
      } finally {
        this.formValues.loader = false;
      }
    },
  },
};
</script>
