// supabase-js-v2/user-management/solid-user-management/src/App.tsx
import { Component, createEffect, createSignal } from 'solid-js';
import { supabase } from './supabaseClient';
import { AuthSession } from '@supabase/supabase-js';
import Account from './Account';
import Auth from './Auth';

const App: Component = () => {
  const [session, setSession] = createSignal<AuthSession | null>(null)

  createEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      setSession(session)
    })

    supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session)
    })
  })
  
  return (
    <div class="container" style={{ padding: '50px 0 100px 0' }}>
      {!session() ? (
        <Auth />
      ) : (
        <Account session={session()!} />
      )}
    </div>
  );
};

export default App;

// supabase-js-v2/user-management/expo-user-management/App.tsx
import 'react-native-url-polyfill/auto'
import { useState, useEffect } from 'react'
import { supabase } from './lib/supabase'
import Auth from './components/Auth'
import Account from './components/Account'
import { View } from 'react-native'
import { Session } from '@supabase/supabase-js'

export default function App() {
  const [session, setSession] = useState<Session | null>(null)

  useEffect(() => {
    supabase.auth.getSession().then(({ session }) => {
      setSession(session)
    })

    supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session)
    })
  }, [])

  return (
    <View>
      {session && session.user ? <Account key={session.user.id} session={session} /> : <Auth />}
    </View>
  )
}
