// supabase-js-v2/user-management/nuxtjs-user-management/pages/index.vue
<template>
  <div class="container" style="padding: 50px 0 100px">
    <Auth  v-if="!state.session" />
    <div class="row" v-else>
      <div class="col-6">
        <h3>Account</h3>
        <Account :session="state.session" />
      </div>
      <div class="col-6">
        <h3>Public Profiles</h3>
        <template v-if="state.profiles.length > 0">
          <ProfileList :profiles="state.profiles" />
        </template>
      </div>
    </div>
  </div>
</template>

<script>
import { supabase } from "../lib/supabaseClient";
export default {
  data() {
    return {
      state: {
        session: null,
        profiles: [],
      },
    };
  },
  mounted() {
    supabase.auth.getSession().then(({ session }) => {
      this.state.session = session;
    });

    supabase.auth.onAuthStateChange((_event, session) => {
      this.state.session = session;
    });

    this.getPublicProfiles();
  },
  methods: {
    async getPublicProfiles() {
      try {
        const { data, error } = await supabase
          .from("profiles")
          .select("id, username, avatar_url, website, updated_at")
          .order("updated_at", { ascending: false });

        if (error || !data) {
          throw error || new Error("No data");
        }
        console.log("data", data);
        this.state.profiles = data;
      } catch (error) {
        console.log("error", error.message);
      }
    },
  },
};
</script>

// supabase-js-v2/user-management/nextjs-ts-user-management/pages/index.tsx
import Auth from '../components/Auth'
import Account from '../components/Account'
import ProfileList from '../components/ProfileList'
import { useState, useEffect } from 'react'
import { supabase } from '../lib/supabaseClient'
import { AuthSession } from '@supabase/supabase-js'
import { Profile } from '../lib/constants'
import Footer from '../components/Footer'

export default function Home() {
  const [session, setSession] = useState<AuthSession | null>(null)
  const [profiles, setProfiles] = useState<Profile[]>([])

  useEffect(() => {
    const fetchData = async () => {
      const data = await supabase.auth.getSession()
      return data
    }

    fetchData()
      .then(({ session }) => {
        setSession(session)
      })
      .catch((error) => {
        console.log(error)
      })

    supabase.auth.onAuthStateChange((_event: string, session: AuthSession | null) => {
      setSession(session)
    })
  }, [session])

  useEffect(() => {
    getPublicProfiles()
  }, [])

  async function getPublicProfiles() {
    try {
      const { data, error } = await supabase
        .from<Profile>('profiles')
        .select('id, username, avatar_url, website, updated_at')
        .order('updated_at', { ascending: false })

      if (error || !data) {
        throw error || new Error('No data')
      }
      console.log('Public profiles:', data)
      setProfiles(data)
    } catch (error) {
      console.log('error', error.message)
    }
  }

  return (
    <div className="container" style={{ padding: '50px 0 100px 0' }}>
      {!session ? (
        <Auth />
      ) : (
        <div className="row">
          <div className="col-6">
            <h3>Account</h3>
            <Account key={session.user.id} session={session} />
          </div>
          <div className="col-6">
            <h3>Public Profiles</h3>
            <ProfileList profiles={profiles} />
          </div>
        </div>
      )}

      <Footer />
    </div>
  )
}
