// supabase-js-v2/user-management/react-user-management/src/App.js
import './index.css'
import { useState, useEffect } from 'react'
import { supabase } from './supabaseClient'
import Auth from './Auth'
import Account from './Account'

export default function Home() {
  const [session, setSession] = useState(null)

  useEffect(() => {
    const fetchData = async () => {
      const { data } = await supabase.auth.getSession()
      return data
    }

    if (!session) {
      fetchData()
      .then(({ session }) => {
        setSession(session)
      })
      .catch((error) => {
        console.log(error)
      })
    }

    supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session)
    })
  }, [session])

  return (
    <div className="container" style={{ padding: '50px 0 100px 0' }}>
      {!session ? <Auth /> : <Account key={session.user.id} session={session} />}
    </div>
  )
}

// supabase-js-v2/user-management/solid-user-management/src/App.tsx
import { Component, createEffect, createSignal } from 'solid-js';
import { supabase } from './supabaseClient';
import { AuthSession } from '@supabase/supabase-js';
import Account from './Account';
import Auth from './Auth';

const App: Component = () => {
  const [session, setSession] = createSignal<AuthSession | null>(null)

  createEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      setSession(session)
    })

    supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session)
    })
  })
  
  return (
    <div class="container" style={{ padding: '50px 0 100px 0' }}>
      {!session() ? (
        <Auth />
      ) : (
        <Account session={session()!} />
      )}
    </div>
  );
};

export default App;
