// supabase-js-v2/user-management/solid-user-management/src/Account.tsx
import { AuthSession } from '@supabase/supabase-js'
import { Component, createEffect, createSignal } from 'solid-js'
import Avatar from './Avatar'
import { supabase } from './supabaseClient'

interface Props {
	session: AuthSession
}

const Account: Component<Props> = ({ session }) => {
  const [loading, setLoading] = createSignal(true)
  const [username, setUsername] = createSignal<string|null>(null)
  const [website, setWebsite] = createSignal<string|null>(null)
  const [avatarUrl, setAvatarUrl] = createSignal<string|null>(null)

  createEffect(() => {
    getProfile()
  })

  const getProfile = async () => {
    try {
      setLoading(true)
      const { user } = session

      let { data, error, status } = await supabase
        .from('profiles')
        .select(`username, website, avatar_url`)
        .eq('id', user.id)
        .single()

      if (error && status !== 406) {
        throw error
      }

      if (data) {
        setUsername(data.username)
        setWebsite(data.website)
        setAvatarUrl(data.avatar_url)
      }
    } catch (error) {
      if (error instanceof Error) {
        alert(error.message)
      }
    } finally {
      setLoading(false)
    }
  }

	const updateProfile = async (e: Event) => {
    e.preventDefault()

    try {
      setLoading(true)
      const { user } = session

      const updates = {
        id: user.id,
        username: username(),
        website: website(),
        avatar_url: avatarUrl(),
        updated_at: (new Date()).toISOString(),
      }

      let { error } = await supabase.from('profiles').upsert(updates)

      if (error) {
        throw error
      }
    } catch (error) {
			if (error instanceof Error) {
				alert(error.message)
			}
    } finally {
      setLoading(false)
    }
  }

	return (
		<div aria-live="polite">
			<form onSubmit={updateProfile} class="form-widget">
				<Avatar 
					url={avatarUrl()} 
					size={150} 
					onUpload={(e: Event, url: string) => {
						setAvatarUrl(url)
						updateProfile(e)
					}} 
				/>
				<div>Email: {session.user.email}</div>
				<div>
					<label for="username">Name</label>
					<input
						id="username"
						type="text"
						value={username() || ''}
						onChange={(e) => setUsername(e.currentTarget.value)}
					/>
				</div>
				<div>
					<label for="website">Website</label>
					<input
						id="website"
						type="text"
						value={website() || ''}
						onChange={(e) => setWebsite(e.currentTarget.value)}
					/>
				</div>
				<div>
					<button
						type="submit"
						class="button primary block"
						disabled={loading()}
					>
						{loading() ? 'Saving ...' : 'Update profile' }
					</button>
				</div>
				<button
					type="button"
					class="button block"
					onClick={() => supabase.auth.signOut()}
				>
					Sign Out
				</button>
			</form>
    </div>
	)
}

export default Account

// supabase-js-v2/user-management/sveltekit-user-management/src/routes/Account.svelte
<script lang="ts">
	import { onMount } from 'svelte'
	import type { AuthSession } from '@supabase/supabase-js'
	import { supabaseClient } from '$lib/db'
	import Avatar from './Avatar.svelte'

	export let session: AuthSession

	let loading = false
	let username: string | null = null
	let website: string | null = null
	let avatarUrl: string | null = null

	onMount(() => {
		getProfile()
	})

	const getProfile = async () => {
		try {
			loading = true
			const { user } = session

			const { data, error, status } = await supabaseClient
				.from('profiles')
				.select(`username, website, avatar_url`)
				.eq('id', user.id)
				.single()

			if (data) {
				username = data.username
				website = data.website
				avatarUrl = data.avatar_url
			}

			if (error && status !== 406) throw error
		} catch (error) {
			if (error instanceof Error) {
				alert(error.message)
			}
		} finally {
			loading = false
		}
	}

	async function updateProfile() {
		try {
			loading = true
			const { user } = session

			const updates = {
				id: user.id,
				username,
				website,
				avatar_url: avatarUrl,
				updated_at: new Date()
			}

			let { error } = await supabaseClient.from('profiles').upsert(updates)

			if (error) throw error
		} catch (error) {
			if (error instanceof Error) {
				alert(error.message)
			}
		} finally {
			loading = false
		}
	}

	async function signOut() {
		try {
			loading = true
			let { error } = await supabaseClient.auth.signOut()
			if (error) throw error
		} catch (error) {
			if (error instanceof Error) {
				alert(error.message)
			}
		} finally {
			loading = false
		}
	}
</script>

<form class="form-widget" on:submit|preventDefault={updateProfile}>
	<Avatar bind:url={avatarUrl} size={10} on:upload={updateProfile} />
	<div>
		<label for="email">Email</label>
		<input id="email" type="text" value={session.user.email} disabled />
	</div>
	<div>
		<label for="username">Name</label>
		<input id="username" type="text" bind:value={username} />
	</div>
	<div>
		<label for="website">Website</label>
		<input id="website" type="website" bind:value={website} />
	</div>

	<div>
		<input
			type="submit"
			class="button block primary"
			value={loading ? 'Loading...' : 'Update'}
			disabled={loading}
		/>
	</div>

	<div>
		<button class="button block" on:click={signOut} disabled={loading}> Sign Out </button>
	</div>
</form>
